Improve site icons
currenjin/site-for-developers pull request #28
Opened 2024-02-14 12:19 UTC by rivercory

마크다운 헤더를 개선해 보았습니다.
추후에 스타일 관련 가이드도 생성할 예정입니다!

2024-02-15 04:27 UTC, currenjin commented
와 ㅋㅋ 아이콘 귀여운데요?

2024-02-15 05:09 UTC, currenjin commented on README.md
> +## 리스트 🧾
리스트라는 표현이 모호한 것 같습니다!
추천 리스트(이것도 맘에 들진 않지만),, 등의 표현은 어떨까요

2024-02-15 05:11 UTC, rivercory commented on README.md
> +### Other
추후 목록 추가를 위해 생성해 두었습니다!

2024-02-15 05:11 UTC, rivercory commented on README.md
> +## 리스트 🧾
자료 모음, 목록 등의 단어는 어떤가요?

2024-02-15 06:35 UTC, currenjin commented on README.md
> +## 리스트 🧾
자료모음 좋아요!

2024-02-15 06:36 UTC, currenjin commented on README.md
> +### Other
해당 목록이 존재하는 상태가 아니라면 제거하는게 좋을 것 같습니다

만약, 넣으실거면 넣어주시구요!

2024-02-15 11:36 UTC, rivercory commented
변경사항 커밋했습니다!

2024-02-15 14:45 UTC, currenjin requested changes

2024-02-15 14:45 UTC, currenjin commented on README.md
> +- [리스트](#리스트-)
자료모음!

2024-02-15 23:32 UTC, rivercory commented on README.md
> +- [리스트](#리스트-)
해결했습니다!

2024-02-16 01:20 UTC, currenjin requested changes

2024-02-16 01:20 UTC, currenjin commented on README.md
> +- [문서](#문서-📃)
URL인코딩에서 이모지는 인지하지 못하기 때문에 다 지워줘야 합니다!

2024-02-16 01:29 UTC, rivercory commented on README.md
> +- [문서](#문서-📃)
해결했습니다

2024-02-16 01:54 UTC, currenjin approved these changes
LGTM ! 감사합니당

2024-02-16 01:54 UTC, merged